# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-06 22:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_with_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
